---
- hosts: all
  gather_facts: True

  vars:
    nodejs_version: "6"
    debian_repo_version: "6.x"
    site_name: machinomy.com
    site_dir: "/srv/www/{{site_name}}"
    letsencrypt_email: sergey.ukustov@machinomy.com

  tasks:

    - name: Install dependencies locally
      local_action: "command yarn install"

    - name: Build locally
      local_action: "command yarn build"

    - name: Make /srv/www/machinomy.com folder
      file:
        path: "{{site_dir}}"
        recurse: yes
        state: directory
        owner: "{{ansible_user_id}}"
      become: yes
      become_user: root

    - name: Copy files
      synchronize:
        src: ../../dist/
        dest: "{{site_dir}}"

    - name: Install nginx
      apt:
        pkg: nginx
        state: installed
      become: yes
      become_user: root

    - name: Install Let's Encrypt package
      apt:
        pkg: letsencrypt
        state: installed
      become: yes

    - name: Set up Let's Encrypt
      command: "letsencrypt certonly --webroot --keep-until-expiring --agree-tos --email {{ letsencrypt_email }} -w {{ site_dir }}/dist -d {{ site_name }} -d www.{{ site_name }}"
      become: yes

    - name: Set up DH params
      command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
      args:
        creates: /etc/ssl/certs/dhparam.pem
      become: yes

    - name: Deactivate the default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: yes
      become_user: root

    - name: Copy the site config
      template:
        src: templates/site.conf.j2
        dest: "/etc/nginx/sites-available/{{site_name}}.conf"
      become: yes
      become_user: root

    - name: Activate the site
      file:
        src: "/etc/nginx/sites-available/{{site_name}}.conf"
        dest: "/etc/nginx/sites-enabled/{{site_name}}.conf"
        state: link
      become: yes
      become_user: root

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
      become: yes
      become_user: root